version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    environment:
      - JWT_SECRET=your_secret_key_here
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - COOKIE_DOMAIN=.sso.local
    networks:
      - sso-network

  app1:
    build: ./app1
    ports:
      - "8080:80"
    environment:
      - VITE_AUTH_URL=http://sso.local:5001
    networks:
      - sso-network

  app2:
    build: ./app2
    ports:
      - "8081:80"
    environment:
      - VITE_AUTH_URL=http://sso.local:5001
    networks:
      - sso-network

networks:
  sso-network:
    driver: bridge
